# Generated by Django 5.2.17 on 2026-09-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='案号')),
                ('title', models.CharField(max_length=200, verbose_name='案件名称')),
                ('case_type', models.CharField(choices=[('civil', '民事'), ('criminal', '刑事'), ('administrative', '行政'), ('arbitration', '仲裁'), ('nonlit', '非诉讼')], default='civil', max_length=20, verbose_name='案件类型')),
                ('stage', models.CharField(choices=[('filing', '立案'), ('first', '一审'), ('second', '二审'), ('retrial', '再审'), ('enforcement', '执行'), ('closed', '结案')], default='filing', max_length=20, verbose_name='诉讼阶段')),
                ('cause', models.CharField(blank=True, max_length=100, verbose_name='案由')),
                ('court', models.CharField(blank=True, max_length=100, verbose_name='受理法院/仲裁机构')),
                ('filed_date', models.DateField(blank=True, null=True, verbose_name='立案日期')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='标的额(元)')),
                ('description', models.TextField(blank=True, verbose_name='案情简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('bar_number', models.CharField(max_length=50, unique=True, verbose_name='执业证号')),
                ('title', models.CharField(choices=[('partner', '合伙人'), ('senior', '资深律师'), ('lawyer', '律师'), ('assistant', '律师助理')], default='lawyer', max_length=20, verbose_name='职称')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='姓名/名称')),
                ('party_type', models.CharField(choices=[('person', '自然人'), ('org', '法人/组织')], default='person', max_length=10, verbose_name='类型')),
                ('id_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='身份证号/统一社会信用代码')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='事项')),
                ('deadline_type', models.CharField(choices=[('appeal', '上诉期限'), ('evidence', '举证期限'), ('defense', '答辩期限'), ('hearing', '开庭'), ('payment', '缴费期限'), ('retrial', '再审申请期限'), ('enforcement', '申请执行期限'), ('other', '其他')], default='other', max_length=20, verbose_name='期限类型')),
                ('due_date', models.DateField(verbose_name='截止日期')),
                ('remind_days', models.IntegerField(default=7, verbose_name='提前提醒天数')),
                ('is_done', models.BooleanField(default=False, verbose_name='已办结')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='cases.case')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_time', models.DateTimeField(verbose_name='开庭时间')),
                ('location', models.CharField(max_length=100, verbose_name='开庭地点')),
                ('judge', models.CharField(blank=True, max_length=50, verbose_name='承办法官/仲裁员')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case')),
            ],
            options={
                'ordering': ['hearing_time'],
            },
        ),
        migrations.CreateModel(
            name='CaseLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', '主办律师'), ('assist', '协办律师')], default='lead', max_length=10, verbose_name='承办角色')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.lawyer')),
            ],
            options={
                'unique_together': {('case', 'lawyer')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='lawyers',
            field=models.ManyToManyField(related_name='cases', through='cases.CaseLawyer', to='cases.lawyer'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='材料名称')),
                ('submitted_to', models.CharField(blank=True, max_length=100, verbose_name='提交对象')),
                ('submit_date', models.DateField(blank=True, null=True, verbose_name='提交日期')),
                ('status', models.CharField(choices=[('pending', '待提交'), ('submitted', '已提交'), ('accepted', '已签收')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='cases.case')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('plaintiff', '原告'), ('defendant', '被告'), ('third', '第三人'), ('appellant', '上诉人'), ('appellee', '被上诉人'), ('applicant', '申请执行人'), ('respondent', '被执行人'), ('suspect', '犯罪嫌疑人'), ('victim', '被害人')], max_length=20, verbose_name='诉讼地位')),
                ('is_client', models.BooleanField(default=False, verbose_name='是否本所客户')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.party')),
            ],
            options={
                'unique_together': {('case', 'party', 'role')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='parties',
            field=models.ManyToManyField(related_name='cases', through='cases.CaseParty', to='cases.party'),
        ),
        migrations.CreateModel(
            name='StageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('filing', '立案'), ('first', '一审'), ('second', '二审'), ('retrial', '再审'), ('enforcement', '执行'), ('closed', '结案')], max_length=20, verbose_name='阶段')),
                ('log_date', models.DateField(verbose_name='日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='cases.case')),
            ],
            options={
                'ordering': ['log_date', 'id'],
            },
        ),
    ]
