# Generated by Django 5.2.17 on 2026-09-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='合并时间'),
        ),
        migrations.AddField(
            model_name='party',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_parties', to='cases.party', verbose_name='合并至主档'),
        ),
        migrations.AddField(
            model_name='party',
            name='source_system',
            field=models.CharField(blank=True, default='案件登记', max_length=100, verbose_name='原档来源'),
        ),
        migrations.CreateModel(
            name='PartyMergeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100, verbose_name='旧档名称')),
                ('source_system', models.CharField(blank=True, default='案件登记', max_length=100, verbose_name='原档来源')),
                ('source_snapshot', models.JSONField(default=dict, verbose_name='旧档快照')),
                ('field_resolutions', models.JSONField(default=dict, verbose_name='冲突信息确认结果')),
                ('relation_resolutions', models.JSONField(default=dict, verbose_name='涉案关系处理结果')),
                ('warnings_confirmed', models.JSONField(default=list, verbose_name='已核实提示')),
                ('operator', models.CharField(blank=True, max_length=80, verbose_name='经办人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_records_as_master', to='cases.party', verbose_name='主档')),
                ('source_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_records_as_source', to='cases.party', verbose_name='被合并旧档')),
            ],
            options={
                'verbose_name': '当事人合并记录',
                'verbose_name_plural': '当事人合并记录',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='旧名称')),
                ('source_system', models.CharField(blank=True, default='案件登记', max_length=100, verbose_name='原档来源')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='cases.party', verbose_name='主档当事人')),
                ('source_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='given_aliases', to='cases.party', verbose_name='来源旧档')),
            ],
            options={
                'verbose_name': '当事人旧名称',
                'verbose_name_plural': '当事人旧名称',
                'ordering': ['-created_at', 'id'],
                'unique_together': {('party', 'name')},
            },
        ),
    ]
