# Generated by Django 5.2.17 on 2026-09-15 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='复核单号')),
                ('proposed_role', models.CharField(choices=[('plaintiff', '原告'), ('defendant', '被告'), ('third', '第三人'), ('appellant', '上诉人'), ('appellee', '被上诉人'), ('applicant', '申请执行人'), ('respondent', '被执行人'), ('suspect', '犯罪嫌疑人'), ('victim', '被害人')], max_length=20, verbose_name='拟列诉讼地位')),
                ('proposed_is_client', models.BooleanField(default=False, verbose_name='是否拟作为本所客户')),
                ('apply_remark', models.TextField(blank=True, verbose_name='申请说明')),
                ('snapshot', models.JSONField(default=dict, verbose_name='风险依据快照')),
                ('risk_level', models.CharField(default='low', max_length=10, verbose_name='风险等级')),
                ('has_prohibited', models.BooleanField(default=False, verbose_name='含本所禁止性冲突')),
                ('needs_exception', models.BooleanField(default=False, verbose_name='须例外授权')),
                ('relationship_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='关系指纹')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('returned', '退回补充材料'), ('superseded', '已重新复核'), ('invalid', '已失效(关系变更)')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('decision_remark', models.TextField(blank=True, verbose_name='复核意见')),
                ('exception_basis', models.TextField(blank=True, verbose_name='例外授权依据')),
                ('exception_expire_date', models.DateField(blank=True, null=True, verbose_name='例外适用期限')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='决定时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='承接使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_reviews', to='cases.lawyer', verbose_name='申请人')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflict_reviews', to='cases.case', verbose_name='目标案件')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflict_reviews', to='cases.party', verbose_name='拟承接当事人')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_reviews', to='cases.lawyer', verbose_name='指定复核人')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_reviews', to='cases.conflictreview', verbose_name='重新复核单')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_reviews', to='cases.lawyer', verbose_name='承接经办人')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConflictReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('apply', '提交申请'), ('supplement', '补充材料'), ('approve', '批准'), ('reject', '拒绝'), ('return', '退回补充材料'), ('supersede', '重新复核'), ('invalidate', '关系变更失效'), ('use', '承接使用')], max_length=20, verbose_name='动作')),
                ('actor_name', models.CharField(blank=True, max_length=50, verbose_name='操作人姓名(留痕)')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_logs', to='cases.lawyer', verbose_name='操作人')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cases.conflictreview', verbose_name='复核单')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConflictReviewMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('material_type', models.CharField(blank=True, max_length=50, verbose_name='材料类型')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='来源/出具方')),
                ('remark', models.TextField(blank=True, verbose_name='说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='cases.conflictreview', verbose_name='复核单')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_materials', to='cases.lawyer', verbose_name='提交人')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
