# Generated by Django 5.2.17 on 2026-09-15 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待接收人核对'), ('returned', '已退回补充'), ('completed', '已完成交接'), ('canceled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='交接原因')),
                ('items_hash', models.CharField(blank=True, max_length=64, verbose_name='清单指纹')),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True, verbose_name='清单刷新时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交核对时间')),
                ('returned_reason', models.TextField(blank=True, verbose_name='退回原因')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='取消原因')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='cases.case')),
                ('from_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_from', to='cases.lawyer', verbose_name='交出人')),
                ('to_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_to', to='cases.lawyer', verbose_name='接收人')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HandoverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '发起交接'), ('submit', '提交核对'), ('return', '退回补充'), ('confirm', '确认接管'), ('cancel', '取消交接'), ('refresh', '补入变更待办'), ('edit', '调整清单')], max_length=20, verbose_name='操作')),
                ('actor_name', models.CharField(max_length=50, verbose_name='操作人姓名')),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.lawyer', verbose_name='操作人')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cases.casehandover')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HandoverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('deadline', '未办期限'), ('hearing', '后续开庭'), ('material', '待提交材料'), ('custom', '其他事项')], max_length=20, verbose_name='事项类型')),
                ('ref_id', models.IntegerField(blank=True, null=True, verbose_name='源对象ID')),
                ('title', models.CharField(max_length=200, verbose_name='事项')),
                ('detail', models.CharField(blank=True, max_length=300, verbose_name='详情')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('hearing_time', models.DateTimeField(blank=True, null=True, verbose_name='开庭时间')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='是否逾期')),
                ('destination', models.CharField(choices=[('takeover', '接收人接管'), ('keep', '原责任人继续办理'), ('void', '无需办理')], default='takeover', max_length=20, verbose_name='去向')),
                ('checked', models.BooleanField(default=False, verbose_name='接收人已核对')),
                ('check_note', models.CharField(blank=True, max_length=200, verbose_name='核对备注')),
                ('change_flag', models.CharField(blank=True, choices=[('new', '新增'), ('changed', '已变更'), ('removed', '已办结/删除'), ('', '')], default='', max_length=10, verbose_name='清单变更标记')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cases.casehandover')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('handover', 'item_type', 'ref_id')},
            },
        ),
    ]
