# Generated by Django 5.2.17 on 2026-09-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称/期限事项')),
                ('deadline_type', models.CharField(choices=[('appeal', '上诉期限'), ('evidence', '举证期限'), ('defense', '答辩期限'), ('hearing', '开庭'), ('payment', '缴费期限'), ('retrial', '再审申请期限'), ('enforcement', '申请执行期限'), ('other', '其他')], default='other', max_length=20, verbose_name='期限类型')),
                ('event_type', models.CharField(choices=[('service', '送达'), ('filing', '立案'), ('judgment', '裁判文书送达'), ('hearing', '开庭通知'), ('other', '其他事件')], max_length=20, verbose_name='触发事件')),
                ('duration_days', models.PositiveIntegerField(verbose_name='期限天数')),
                ('day_type', models.CharField(choices=[('natural', '自然日'), ('workday', '工作日')], default='natural', max_length=20, verbose_name='日期口径')),
                ('start_timing', models.CharField(choices=[('event_day', '事件发生当日'), ('next_day', '事件次日')], default='next_day', max_length=20, verbose_name='起算点')),
                ('holiday_postpone', models.BooleanField(default=True, verbose_name='届满日遇节假日顺延')),
                ('remind_days', models.PositiveIntegerField(default=7, verbose_name='提前提醒天数')),
                ('escalate_days', models.PositiveIntegerField(default=3, verbose_name='逾期升级天数')),
                ('owner_role', models.CharField(choices=[('lead', '主办律师'), ('assist', '协办律师')], default='lead', max_length=20, verbose_name='默认负责人角色')),
                ('reviewer_role', models.CharField(choices=[('lead', '主办律师'), ('assist', '协办律师')], default='assist', max_length=20, verbose_name='默认复核人角色')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '期限规则',
                'verbose_name_plural': '期限规则',
                'ordering': ['event_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('change_type', models.CharField(choices=[('created', '创建'), ('manual_update', '人工修改'), ('event_recalculate', '事件更正重算'), ('rule_recalculate', '规则调整重算'), ('event_revoked', '事件撤销')], max_length=30, verbose_name='变更类型')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='变更原因')),
                ('snapshot', models.JSONField(default=dict, verbose_name='期限快照')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField(unique=True, verbose_name='放假日期')),
                ('name', models.CharField(max_length=100, verbose_name='节假日名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '节假日',
                'verbose_name_plural': '节假日',
                'ordering': ['holiday_date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(choices=[('owner', '负责人'), ('reviewer', '复核人')], max_length=20, verbose_name='接收角色')),
                ('kind', models.CharField(choices=[('advance', '到期提醒'), ('overdue', '逾期提醒'), ('escalation', '逾期升级')], max_length=20, verbose_name='提醒类型')),
                ('scheduled_at', models.DateTimeField(verbose_name='计划发送时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='发送次数')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='下次补发时间')),
                ('last_error', models.CharField(blank=True, max_length=200, verbose_name='最近失败原因')),
                ('dedupe_key', models.CharField(max_length=120, unique=True, verbose_name='幂等键')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='deadline',
            name='basis_text',
            field=models.TextField(blank=True, verbose_name='起算依据'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='办结时间'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='escalate_days',
            field=models.PositiveIntegerField(default=3, verbose_name='逾期升级天数'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='lifecycle',
            field=models.CharField(choices=[('active', '有效'), ('revoked', '因事件撤销'), ('superseded', '已被替代')], default='active', max_length=20, verbose_name='生命周期'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deadlines', to='cases.lawyer', verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deadlines', to='cases.lawyer', verbose_name='复核人'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='revoked_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='失效原因'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='source',
            field=models.CharField(choices=[('manual', '人工登记'), ('generated', '规则生成')], default='manual', max_length=20, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DeadlineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('service', '送达'), ('filing', '立案'), ('judgment', '裁判文书送达'), ('hearing', '开庭通知'), ('other', '其他事件')], max_length=20, verbose_name='事件类型')),
                ('title', models.CharField(max_length=100, verbose_name='事件名称')),
                ('event_date', models.DateField(verbose_name='事件日期')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='外部事件流水号')),
                ('status', models.CharField(choices=[('active', '有效'), ('revoked', '已撤销')], default='active', max_length=20, verbose_name='状态')),
                ('revoked_reason', models.CharField(blank=True, max_length=200, verbose_name='撤销原因')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadline_events', to='cases.case')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='deadline',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deadlines', to='cases.deadlineevent', verbose_name='起算事件'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlines', to='cases.deadlinerule', verbose_name='生成规则'),
        ),
        migrations.AddConstraint(
            model_name='deadline',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False), ('lifecycle', 'active'), ('rule__isnull', False)), fields=('event', 'rule'), name='uniq_active_generated_deadline'),
        ),
        migrations.AddField(
            model_name='deadlineversion',
            name='deadline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cases.deadline'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='deadline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='cases.deadline'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='cases.lawyer', verbose_name='接收人'),
        ),
        migrations.AddConstraint(
            model_name='deadlineevent',
            constraint=models.UniqueConstraint(fields=('case', 'event_type', 'event_date', 'title'), name='uniq_deadline_event_identity'),
        ),
        migrations.AlterUniqueTogether(
            name='deadlineversion',
            unique_together={('deadline', 'version')},
        ),
    ]
