# Generated by Django 5.2.17 on 2026-09-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=30, unique=True, verbose_name='账单编号')),
                ('title', models.CharField(max_length=100, verbose_name='期次/说明')),
                ('issue_date', models.DateField(verbose_name='出账日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='付款期限')),
                ('reduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='减免金额(元)')),
                ('reduction_reason', models.CharField(blank=True, max_length=200, verbose_name='减免原因')),
                ('status', models.CharField(choices=[('open', '待收款'), ('partial', '部分收款'), ('paid', '已结清'), ('void', '已冲正')], default='open', max_length=10, verbose_name='状态')),
                ('void_reason', models.CharField(blank=True, max_length=200, verbose_name='冲正原因')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='冲正时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='cases.case')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(verbose_name='费用日期')),
                ('category', models.CharField(choices=[('court_fee', '诉讼费/仲裁费'), ('travel', '差旅费'), ('notary', '公证费'), ('appraisal', '鉴定费'), ('courier', '快递/文印'), ('other', '其他')], default='other', max_length=20, verbose_name='费用类别')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额(元)')),
                ('description', models.CharField(max_length=200, verbose_name='费用说明')),
                ('status', models.CharField(choices=[('pending', '待核准'), ('approved', '已核准'), ('billed', '已出账')], default='pending', max_length=10, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='核准时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cases.case')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.lawyer', verbose_name='代垫人')),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeeAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('fixed', '固定收费'), ('hourly', '按工时收费')], default='hourly', max_length=10, verbose_name='收费方式')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='固定收费总额(元)')),
                ('notes', models.TextField(blank=True, verbose_name='约定说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_agreement', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额(元)')),
                ('received_date', models.DateField(verbose_name='收款日期')),
                ('method', models.CharField(choices=[('bank', '银行转账'), ('cash', '现金'), ('check', '支票'), ('other', '其他')], default='bank', max_length=10, verbose_name='收款方式')),
                ('is_reversal', models.BooleanField(default=False, verbose_name='冲正退款')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cases.bill')),
            ],
            options={
                'ordering': ['received_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='工作日期')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='工时(小时)')),
                ('description', models.CharField(max_length=200, verbose_name='工作内容')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='适用费率快照(元/小时)')),
                ('status', models.CharField(choices=[('pending', '待核准'), ('approved', '已核准'), ('billed', '已出账')], default='pending', max_length=10, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='核准时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='cases.case')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.lawyer')),
            ],
            options={
                'ordering': ['-work_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('time', '工时费'), ('expense', '代垫费用'), ('fixed', '固定收费')], max_length=10, verbose_name='明细类型')),
                ('description', models.CharField(max_length=200, verbose_name='摘要')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='数量(工时)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价/费率(元)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额(元)')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cases.bill')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_line', to='cases.expense')),
                ('time_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_line', to='cases.timeentry')),
            ],
        ),
        migrations.CreateModel(
            name='CaseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小时费率(元)')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_rates', to='cases.case')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.lawyer')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
                'unique_together': {('case', 'lawyer', 'effective_date')},
            },
        ),
    ]
