# Generated by Django 5.2.17 on 2026-09-15 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parties', to=settings.AUTH_USER_MODEL, verbose_name='建档人'),
        ),
        migrations.CreateModel(
            name='CaseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', '主办律师'), ('assist', '协办律师'), ('reader', '只读')], default='reader', max_length=10, verbose_name='案件内角色')),
                ('source', models.CharField(choices=[('team', '承办团队'), ('grant', '手动授权')], default='grant', max_length=10, verbose_name='授权来源')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='借阅到期时间')),
                ('revoked', models.BooleanField(default=False, verbose_name='已撤权')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤权时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '案件授权',
                'verbose_name_plural': '案件授权',
                'ordering': ['case_id', 'role', 'user__username'],
                'unique_together': {('case', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('login_failed', '登录失败'), ('logout', '退出登录'), ('grant', '授权'), ('revoke', '撤权'), ('expire', '借阅到期'), ('case_view', '查看案件详情'), ('conflict_check', '利益冲突检索'), ('case_delete', '删除案件')], max_length=20, verbose_name='动作')),
                ('detail', models.CharField(blank=True, max_length=500, verbose_name='详情')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cases.case', verbose_name='相关案件')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL, verbose_name='被授权对象')),
                ('access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cases.caseaccess', verbose_name='相关授权')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('lead', '主办律师'), ('assist', '协办律师'), ('reader', '只读助理')], default='reader', max_length=10, verbose_name='账号角色')),
                ('lawyer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='cases.lawyer', verbose_name='绑定律师档案')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '账号资料',
                'verbose_name_plural': '账号资料',
            },
        ),
    ]
