# Generated by Django 5.2.17 on 2026-09-15 10:35

import cases.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(blank=True, help_text='如 起诉状/证据材料/代理词/申请书', max_length=50, verbose_name='材料类别'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('draft', '未定稿'), ('finalized', '已定稿'), ('submitted', '已提交'), ('signed', '已签收'), ('returned', '退回补正')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='MaterialSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_to', models.CharField(help_text='如 朝阳区人民法院立案庭 / 对方代理律师', max_length=100, verbose_name='接收对象')),
                ('receiver_name', models.CharField(blank=True, max_length=50, verbose_name='接收人')),
                ('method', models.CharField(choices=[('window', '立案/诉讼窗口'), ('online', '网上立案/诉讼平台'), ('post', '邮寄'), ('hand', '当面递交'), ('other', '其他')], default='window', max_length=20, verbose_name='提交方式')),
                ('submit_date', models.DateField(verbose_name='提交日期')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('signed', '已签收'), ('returned', '退回补正')], default='submitted', max_length=20, verbose_name='状态')),
                ('created_by', models.CharField(max_length=50, verbose_name='提交经办人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_submissions', to='cases.case')),
                ('resubmitted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='cases.materialsubmission', verbose_name='补正后重新提交自')),
            ],
            options={
                'ordering': ['-submit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('file', models.FileField(blank=True, help_text='历史补录时可暂缺，之后再上传新版本补件', null=True, upload_to=cases.models.material_file_path, verbose_name='附件')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256')),
                ('change_note', models.CharField(blank=True, help_text='如 根据法官意见修改诉讼请求第二项', max_length=255, verbose_name='版本说明')),
                ('uploaded_by', models.CharField(max_length=50, verbose_name='上传人')),
                ('is_backfilled', models.BooleanField(default=False, help_text='补建历史材料时产生的无附件版本', verbose_name='历史补录')),
                ('is_final', models.BooleanField(default=False, verbose_name='定稿版本')),
                ('finalized_by', models.CharField(blank=True, max_length=50, verbose_name='定稿确认人')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='定稿时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cases.material')),
            ],
            options={
                'ordering': ['material_id', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='审阅人')),
                ('result', models.CharField(choices=[('comment', '意见'), ('revise', '需修改'), ('approve', '同意定稿')], default='comment', max_length=20, verbose_name='审阅结论')),
                ('comment', models.TextField(verbose_name='审阅意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='审阅时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cases.materialversion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='材料名称(快照)')),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号(快照)')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名(快照)')),
                ('copies', models.PositiveIntegerField(default=1, verbose_name='份数')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='页数')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cases.materialsubmission')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_items', to='cases.materialversion')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('signed', '签收回执'), ('returned', '退回补正')], max_length=20, verbose_name='回执类型')),
                ('receipt_no', models.CharField(blank=True, max_length=100, verbose_name='回执/签收编号')),
                ('receiver_name', models.CharField(blank=True, max_length=50, verbose_name='经办人/签收人')),
                ('receipt_date', models.DateField(verbose_name='回执日期')),
                ('file', models.FileField(blank=True, null=True, upload_to=cases.models.receipt_file_path, verbose_name='回执附件')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='回执文件名')),
                ('note', models.TextField(blank=True, help_text='退回补正须注明补正事项；重新提交可在备注中关联', verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='cases.materialsubmission')),
            ],
            options={
                'ordering': ['receipt_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='materialversion',
            constraint=models.UniqueConstraint(fields=('material', 'version_no'), name='uniq_material_version_no'),
        ),
        migrations.AddConstraint(
            model_name='submissionitem',
            constraint=models.UniqueConstraint(fields=('submission', 'version'), name='uniq_submission_version'),
        ),
    ]
