# Generated by Django 5.2.17 on 2026-09-15 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='caselawyer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='party',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='stagelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.CreateModel(
            name='ArchiveVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '整理中'), ('submitted', '待复核'), ('sealed', '已封存'), ('rejected', '复核退回'), ('reopened', '已重开(历史版本)')], default='draft', max_length=20, verbose_name='状态')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='结案日期')),
                ('summary', models.TextField(blank=True, verbose_name='结案摘要')),
                ('fingerprint', models.CharField(blank=True, max_length=64, verbose_name='清单指纹')),
                ('fingerprint_state', models.JSONField(blank=True, default=dict, verbose_name='分区指纹明细')),
                ('prepared_by', models.CharField(blank=True, max_length=50, verbose_name='整理人')),
                ('submitted_by', models.CharField(blank=True, max_length=50, verbose_name='提交人')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('reviewer', models.CharField(blank=True, max_length=50, verbose_name='复核人')),
                ('review_comment', models.TextField(blank=True, verbose_name='复核意见')),
                ('sealed_at', models.DateTimeField(blank=True, null=True, verbose_name='封存时间')),
                ('reject_reason', models.TextField(blank=True, verbose_name='退回原因')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='归档快照')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_versions', to='cases.case')),
            ],
            options={
                'ordering': ['-version_no'],
                'unique_together': {('case', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='ReopenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_type', models.CharField(choices=[('retrial', '再审'), ('supplement', '补充材料'), ('other', '其他')], max_length=20, verbose_name='重开原因')),
                ('reason', models.TextField(verbose_name='原因说明')),
                ('applicant', models.CharField(blank=True, max_length=50, verbose_name='申请人')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '未批准')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approver', models.CharField(blank=True, max_length=50, verbose_name='批准人')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('next_stage', models.CharField(choices=[('filing', '立案'), ('first', '一审'), ('second', '二审'), ('retrial', '再审'), ('enforcement', '执行'), ('closed', '结案')], default='retrial', max_length=20, verbose_name='重开后阶段')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopen_requests', to='cases.archiveversion', verbose_name='申请时卷宗版本')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopen_requests', to='cases.case')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deadline', '未办结期限'), ('material', '未结材料'), ('hearing', '未来庭期'), ('custom', '其他事项')], max_length=20, verbose_name='事项类别')),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联记录ID')),
                ('item_key', models.CharField(max_length=60, verbose_name='事项键')),
                ('title', models.CharField(max_length=200, verbose_name='事项')),
                ('detail', models.CharField(blank=True, max_length=300, verbose_name='详情')),
                ('disposition', models.CharField(blank=True, choices=[('completed', '已完成'), ('handover', '已移交处理'), ('followup', '继续跟进'), ('waived', '当事人放弃/终结'), ('other', '其他处置')], max_length=20, verbose_name='处置方式')),
                ('disposition_note', models.TextField(blank=True, verbose_name='处置说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_items', to='cases.archiveversion')),
            ],
            options={
                'ordering': ['kind', 'id'],
                'unique_together': {('archive_version', 'item_key')},
            },
        ),
    ]
