# Generated by Django 5.2.17 on 2026-09-16 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_bill_expense_feeagreement_payment_timeentry_billline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyer', to=settings.AUTH_USER_MODEL, verbose_name='关联账号'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='cases.payment', verbose_name='红冲的原收款'),
        ),
    ]
